### ISSUE TITLE
Install error on sagemaker

### ISSUE THREAD

**Issue by veve90** [paws-r/paws#337] opened 2020-11-06 11:24 UTC
When I try to use this package on sagemaker I have the following error. 
I tried to install it with devtools, without it, from github... and I allways get the same error...

![image](https://user-images.githubusercontent.com/3790979/98360944-fbca8180-202a-11eb-8994-82bd5af5a434.png)

**Comment by adambanker** [comment] 2020-11-06 12:47
Thank you for leaving an issue! Can you give me more information on the SageMaker setup you are using so that I can try to reproduce the bug? Are you using Jupyter or JupyterLab? Which kernel are you using?

**Comment by adambanker** [comment] 2020-11-15 17:15
Hi, are you still having this issue? I was able to install paws on SageMaker without any issues when I used the R kernel in JupyterLab on a ml.t2.medium instance. Is this the same/similar to the environment that you were using? Please let me know what your setup was so I can attempt to replicate the issue. Otherwise I will close this issue due to inactivity. Thanks

**Comment by davidkretch** [comment] 2020-12-17 00:15
Hello, we're closing this for now. Please let us know if this is still an issue and we'll do our best!

**Closed by davidkretch** 2020-12-17 00:15 UTC
